### ISSUE TITLE
UnhandledPromiseRejectionWarning で止まる

### ISSUE THREAD

**Issue by oti** [decomoji/slack-reaction-decomoji#103]
UnhandledPromiseRejectionWarning でプロセスが停止する現象を確認している。発生条件がいくつかあるもよう。

オブジェクトのプロパティを引き当てられなかったとき:
```
Register "v5.17.0" starting...
(node:21330) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'name' of 'localDecomojiList[i]' as it is undefined.
    at _pretend (/Users/hoge/decomoji/decomoji/scripts/manager/modules/pretender.js:52:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async pretender (/Users/hoge/decomoji/decomoji/scripts/manager/modules/pretender.js:122:3)
    at async main (/Users/hoge/decomoji/decomoji/scripts/manager/index.js:100:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21330) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21330) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

`goToEmojiPage()` を実行するも目的のページに到達できなかったとき:
```
(node:23145) UnhandledPromiseRejectionWarning: Error: Navigation failed because browser has disconnected!
    at CDPSession.<anonymous> (/Users/hoge/decomoji/decomoji/node_modules/puppeteer/lib/LifecycleWatcher.js:45:131)
    at CDPSession.emit (events.js:315:20)
    at CDPSession._onClosed (/Users/hoge/decomoji/decomoji/node_modules/puppeteer/lib/Connection.js:181:14)
    at Connection._onClose (/Users/hoge/decomoji/decomoji/node_modules/puppeteer/lib/Connection.js:110:21)
    at WebSocket.<anonymous> (/Users/hoge/decomoji/decomoji/node_modules/puppeteer/lib/WebSocketTransport.js:29:30)
    at WebSocket.onClose (/Users/hoge/decomoji/decomoji/node_modules/ws/lib/event-target.js:129:16)
    at WebSocket.emit (events.js:315:20)
    at WebSocket.emitClose (/Users/hoge/decomoji/decomoji/node_modules/ws/lib/websocket.js:191:10)
    at Socket.socketOnClose (/Users/hoge/decomoji/decomoji/node_modules/ws/lib/websocket.js:858:15)
    at Socket.emit (events.js:315:20)
  -- ASYNC --
    at Frame.<anonymous> (/Users/hoge/decomoji/decomoji/node_modules/puppeteer/lib/helper.js:94:19)
    at Page.goto (/Users/hoge/decomoji/decomoji/node_modules/puppeteer/lib/Page.js:485:53)
    at Page.<anonymous> (/Users/hoge/decomoji/decomoji/node_modules/puppeteer/lib/helper.js:95:27)
    at goToEmojiPage (/Users/hoge/decomoji/decomoji/scripts/manager/modules/goToEmojiPage.js:10:14)
    at _pretend (/Users/hoge/decomoji/decomoji/scripts/manager/modules/pretender.js:38:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async pretender (/Users/hoge/decomoji/decomoji/scripts/manager/modules/pretender.js:122:3)
    at async main (/Users/hoge/decomoji/decomoji/scripts/manager/index.js:60:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23145) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23145) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

謎:
```
(node:23336) UnhandledPromiseRejectionWarning: #<ErrorEvent>
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23336) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23336) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

これらは、追加・削除・エイリアス登録・移行・更新の全ての実行モードで発生するが、発生せずプロセスが完了することもある。

**Comment by oti** [comment]
何度か試したとことろ、`ratelimited` が発生して再度ログインしようとした時に UnhandledPromiseRejectionWarning が起こることが多いように思う。

その場合 `goToEmojiPage()` でカスタム絵文字管理ページへ移動しようとした時に発生するエラーなので、Slack本家ウェブサイト側の仕様だとするとデコモジスクリプトからはどうしようもない可能性もある。

あるいは Puppeteer のバージョンが古いのが原因か？

**Comment by oti** [comment]
https://github.com/decomoji/decomoji/commit/21f6913a4089fd24ca373e7a129660f5c0fe0f33 にて Puppeteer を v3 から v8 にアップグレードした。アップグレード後に幾つかのワークスペースで試したが UnhandledPromiseRejectionWarning は発生していない。これで様子を見ることにする……

**Comment by oti** [comment]
`getToEmojiPage()` の実行時に発生する UnhandledPromiseRejectionWarning エラーは、おそらく Puppeteer を v8 にあげたことで直ったが、プロパティが引き当てられなくて発生する UnhandledPromiseRejectionWarning エラーはまだバグとして残っていた。修正方法が判明したので、https://github.com/decomoji/decomoji/commit/c4c96a06b27126e6b2ddf69a1ddf9523c5379614 にて修正した。
