### ISSUE TITLE
登録時に TimeoutError が発生する

### ISSUE THREAD

**Issue by daiking1756** [decomoji/slack-reaction-decomoji#114]
# はじめに
Issue作成した後に、自己解決しました 🙇 
実施したことを記載してCloseしておきます。

# 発生していたエラー
```shell
❯ node scripts/manager
? ワークスペースのサブドメインを入力してください: *****
? メールアドレスを入力してください: *****@*****
? パスワードを入力してください: **********
? モードを選択してください: 登録
? 対象タイプを選択してください: カテゴリーごと
? カテゴリーを選択してください: 基本セット, 拡張セット

workspace      : https://*****.slack.com/
email          : *****@*****
mode           : upload
updateMode     : false
term           : category
configs        : v5_basic,v5_extra
forceRemove    : false

Connecting...

(node:10093) UnhandledPromiseRejectionWarning: TimeoutError: Navigation timeout of 30000 ms exceeded
    at /Users/daiking1756/decomoji/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
    at async FrameManager.waitForFrameNavigation (/Users/daiking1756/decomoji/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:127:23)
    at async Frame.waitForNavigation (/Users/daiking1756/decomoji/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:440:16)
    at async Page.waitForNavigation (/Users/daiking1756/decomoji/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:829:16)
    at async Promise.all (index 1)
    at async goToEmojiPage (/Users/daiking1756/decomoji/scripts/manager/modules/goToEmojiPage.js:33:3)
    at async _upload (/Users/daiking1756/decomoji/scripts/manager/modules/uploader.js:65:14)
    at async uploader (/Users/daiking1756/decomoji/scripts/manager/modules/uploader.js:162:3)
    at async main (/Users/daiking1756/decomoji/scripts/manager/index.js:68:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10093) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10093) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

2FAを有効にしていた場合は、代わりに下記のエラーが発生していました。
```shell
TimeoutError: waiting for selector `#list_emoji_section` failed: timeout 30000ms exceeded
```

**Comment by daiking1756** [comment]
# 試したこと
当初は「基本セット」と「拡張セット」を複数選択して登録処理を実行していました。
試しに「基本セット」だけを選択して登録処理を実行したところ、正しく登録されました。
その後「拡張セット」だけを選択して登録処理を実行したところ、こちらも正しく登録されました。
