### ISSUE TITLE
スクリプトが動かない

### ISSUE THREAD

**Issue by oti** [decomoji/slack-reaction-decomoji#68]
masterブランチで

```bash
cd script
bundle exec ruby import.rb
```

を実行すると、

```
Traceback (most recent call last):
	5: from import.rb:8:in `<main>'
	4: from /Users/oti/Sandbox/decomoji/decomoji/scripts/importer.rb:14:in `import_decomojis'
	3: from /Users/oti/Sandbox/decomoji/decomoji/scripts/importer.rb:53:in `move_to_emoji_page'
	2: from /Users/oti/Sandbox/decomoji/decomoji/scripts/importer.rb:53:in `loop'
	1: from /Users/oti/Sandbox/decomoji/decomoji/scripts/importer.rb:59:in `block in move_to_emoji_page'
/Users/oti/Sandbox/slack-reaction-decomoji/decomoji/scripts/importer.rb:40:in `login': undefined method `email=' for nil:NilClass (NoMethodError)
```

というエラーが返ってきてデコモジの追加が行えません。

おそらくですが、Slack本体がログイン画面を動的なHTMLで構築するように変更したため、ログインページのURLを Mechanize でアクセスして返却されたHTMLには `<form>` 要素が含まれなくなり、ログイン処理が行えないという状況のようです。

ログインページが動的HTMLになった以上、Mechanize 利用のままでは対応できない気がします。Ruby はまともに学習したことがないのでこれに対処するコードを私が書ける自信がありません。

誰か助けてくださると幸いです。

**Comment by oti** [comment]
Ruby はわからないので JS でやろうと #69 を作業中です。

ですがが、もし Ruby スクリプトで解決できる手段があるならできる方に改修をお願いしたいです。一説には Selenium を使うとできるらしいという話をインターネットで見ました。

何卒よろしくお願いいたします。
